replace correlation matrix from production with random matrix, add exact vs exact moments test
when replacing the production matrix with a random one, the suite throws
exactly one error

xassetmodel2.cpp:684: error: in "QuantExtTestSuite/XAsset model tests 2/QuantExt::detail::quantext_test_case(&XAssetModelTest2::testLgm31fPositiveCovariance)": negative eigenvalue at 30 in covariance matrix at t=0.754203 (-2.04911e-14)

but this seems due to numerical reasons (e.g. from the numerical
integration). We adjust the tolerance accordingly.